### ISSUE TITLE
site service died

### ISSUE THREAD

**Issue by tkellen** [bostonjs/bostonjs.com#28]
logs read this:
```
TypeError: Cannot read property '69' of undefined
    at app.get.res.render.meetup (/mnt/6bde25b7f59ee9c67c94d3324e12523f7f0e31e6/app/index.js:29:56)
    at Layer.handle [as handle_request] (/mnt/6bde25b7f59ee9c67c94d3324e12523f7f0e31e6/node_modules/express/lib/router/layer.js:95:5)
    at next (/mnt/6bde25b7f59ee9c67c94d3324e12523f7f0e31e6/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/mnt/6bde25b7f59ee9c67c94d3324e12523f7f0e31e6/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/mnt/6bde25b7f59ee9c67c94d3324e12523f7f0e31e6/node_modules/express/lib/router/layer.js:95:5)
    at /mnt/6bde25b7f59ee9c67c94d3324e12523f7f0e31e6/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/mnt/6bde25b7f59ee9c67c94d3324e12523f7f0e31e6/node_modules/express/lib/router/index.js:330:12)
    at next (/mnt/6bde25b7f59ee9c67c94d3324e12523f7f0e31e6/node_modules/express/lib/router/index.js:271:10)
    at SendStream.error (/mnt/6bde25b7f59ee9c67c94d3324e12523f7f0e31e6/node_modules/express/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:95:17)
```

I ran an npm build and restarted the service and it came back up.

**Comment by ajpiano** [comment]
Hmm sounds like data got out of sync or something. Was a new meetup added recently @kadamwhite?

**Comment by kadamwhite** [comment]
A meetup was re-scheduled this week, the guy running the three.js intro had
to change the date and such.

**Comment by tkellen** [comment]
This happened again. I fixed it the same way.

**Comment by tkellen** [comment]
This happened again. This time the system was out of space. Nginx access and error logs were up to 6gb. I removed these and restarted the site service and it was restored.

**Comment by kadamwhite** [comment]
Thanks, Tyler!

K. Adam White
kadamwhite@gmail.com
401.575.7829

**Comment by tkellen** [comment]
Did this again! `npm run build` + `sudo service site restart`.

It would be really nice if someone looked into the underlying cause of this. I don't quite have the bandwidth to do so.

**Comment by tkellen** [comment]
Fixed again last night.

**Comment by kadamwhite** [comment]
This time I think it died because we ran out of upcoming meet ups: I noticed the site was erroring, so I added a meetup in November and restarted the service. 

K. Adam White
kadamwhite@gmail.com
401-575-7829

**Comment by tkellen** [comment]
Looks like we're down again. @kadamwhite can you help?

**Comment by kadamwhite** [comment]
I missed this; I think it's because we don't properly safeguard against the case where no meetup is scheduled. I'll make an event for December when I get home to see if that fixes it

K. Adam White
kadamwhite@gmail.com
401-575-7829

**Comment by tkellen** [comment]
The server ran out of space this morning and the site stopped responding as a result. I deleted the log file `/var/log/site` and restarted it. @ajpiano, can you investigate the error output and fix whatever is causing this?

**Comment by ajpiano** [comment]
I can but this is going to be hard for me to prioritize. Is there not someone who attends the meetup who's interested in assisting us with site stuff?

Do we just need to add the log/backup rotation clearing @tkellen , do you rekcon?
